export const ROUTES = {
  HOME: '/',
  FILTER: '/filter',
  RESERVATION: '/reservation',
  FOOD_TRUCK_ONBOARDING: '/owner/food-truck-onboarding',
  SET_LOCATION: '/set-location',
  CHATLIST: '/chat-list',
  MESSAGE_LIST: '/owner/message-list',
  MESSAGE_FORM: '/owner/message-form',
  MYPAGE: '/mypage',
  ACCOUNT: '/owner/account',
  ACCOUNT_FORM: '/owner/account-form',
  PROFILE_SETTING: '/profile-setting',
  PROFILE_SETTING_DETAIL: (field: string) => `/profile-setting/${field}`,
};
