export const ROUTES = {
  HOME: '/',
  FILTER: '/filter',
  RESERVATION: '/reservation',
  FOOD_TRUCK_ONBOARDING: '/owner/food-truck-onboarding',
  SET_LOCATION: '/set-location',
  CHATLIST: '/chat-list',
  MESSAGE_LIST: '/owner/message-list',
  MESSAGE_FORM: '/owner/message-form',
  MYPAGE: '/mypage',
  ACCOUNT: '/owner/account',
  ACCOUNT_FORM: '/owner/account-form',
  RESERVATION_HISTORY: '/reservation-history',
  RESERVATION_DETAIL: (reservationId: string) =>
    `/reservation-history/detail/${reservationId}`,
  SAVE_FOOD_TRUCK_LIST: '/save-food-truck-list',
  UPLOAD_FOOD_TRUCK_IMAGES: '/owner/food-truck-form/upload-food-truck-images',
  PROFILE_SETTING: '/profile-setting',
  PROFILE_SETTING_DETAIL: '/profile-setting',
  FOOD_TRUCK_MANAGEMENT: '/owner/food-truck-management',
  MENU_LIST: (foodTruckId: string) => `/owner/menu-list/${foodTruckId}`,
  MENU_REGISTER: (foodTruckId: string) => `/owner/menu-register/${foodTruckId}`,
  MENU_EDIT: (foodTruckId: string, menuId: string) => `/owner/menu-edit/${foodTruckId}/${menuId}`,
  FOOD_TRUCK_FORM: '/owner/food-truck-form',
};
