export const ROUTES = {
  HOME: '/',
  FILTER: '/filter',
  RESERVATION: '/reservation',
  RESERVATION_DETAIL: '/reservation/detail',
  FOOD_TRUCK_ONBOARDING: '/owner/food-truck-onboarding',
  SET_LOCATION: '/set-location',
  CHATLIST: '/chat-list',
  MESSAGE_LIST: '/owner/message-list',
  MESSAGE_FORM: '/owner/message-form',
  MYPAGE: '/mypage',
  ACCOUNT: '/owner/account',
  ACCOUNT_FORM: '/owner/account-form',
  RESERVATION_HISTORY: '/reservation-history',
  SAVE_FOOD_TRUCK_LIST: '/save-food-truck-list',
  UPLOAD_FOOD_TRUCK: '/owner/upload-food-truck',
  PROFILE_SETTING: '/profile-setting',
  PROFILE_SETTING_DETAIL: (field: string) => `/profile-setting/${field}`,
  FOOD_TRUCK_MANAGEMENT: '/owner/food-truck-management',
};
