import { z } from 'zod';
import {
  MENU_TEXT,
  MENU_TEXT_ERROR_MESSAGE
} from '@pages/@owner/menu/constant/menu';

export const MENU_DESCRIPTION_VALIDATOR = z.string()
  .min(
    MENU_TEXT.DESCRIPTION_MIN_LENGTH,
    MENU_TEXT_ERROR_MESSAGE.DESCRIPTION_MIN(MENU_TEXT.DESCRIPTION_MIN_LENGTH)
  )
  .max(
    MENU_TEXT.DESCRIPTION_MAX_LENGTH,
    MENU_TEXT_ERROR_MESSAGE.DESCRIPTION_MAX(MENU_TEXT.DESCRIPTION_MAX_LENGTH)
  );
