export const mockFoodTruck = {
  foodTruckId: 1,
  name: '푸드트럭 이름',
  description: '맛있는 푸드트럭입니다.',
  phoneNumber: '010-1234-5678',
  activeTime: '09:00-20:00',
  timeDiscussRequired: false,
  foodTruckServiceAreas: ['서울 광진구', '서울 강남구', '서울 영등포구'],
  menuCategories: [
    '한식',
    '분식',
    '간식',
    '디저트',
    '한식',
    '분식',
    '간식',
    '디저트',
  ],
  availableQuantity: '200인분 미만',
  needElectricity: '필요',
  paymentMethod: '무관',
  availableDates: '2025-10-01~2025-10-10',
  photoUrl: [
    'https://placehold.co/300',
    'https://placehold.co/300',
    'https://placehold.co/300',
  ],
  operatingInfo: '조금 더 긴 운영정보\n어쩌구 저쩌구 푸드트럭 맛있다.',
  option: '안녕하세요',
  averageRating: 4.5,
  isSaved: true,
};

export const mockMenus = [
  {
    menuId: 9,
    name: '불고기버거',
    price: '7500원',
    description: '신선한 채소와 불고기를 듬뿍 넣은 수제 버거',
    imageUrl: 'https://placehold.co/100',
  },
  {
    menuId: 4,
    name: '핫도그 세트',
    price: '12000원',
    description: '핫도그 + 음료 세트',
    imageUrl: 'https://placehold.co/100',
  },
  {
    menuId: 3,
    name: '불고기 핫도그',
    price: '5000원',
    description: '불고기 소스를 올린 핫도그',
    imageUrl: 'https://placehold.co/100',
  },
  {
    menuId: 1,
    name: '불고기버거',
    price: '7500원',
    description: '신선한 채소와 불고기를 듬뿍 넣은 수제 버거',
    imageUrl: 'https://placehold.co/100',
  },
  {
    menuId: 2,
    name: '핫도그 세트',
    price: '12000원',
    description: '핫도그 + 음료 세트',
    imageUrl: 'https://placehold.co/100',
  },
  {
    menuId: 6,
    name: '불고기 핫도그',
    price: '5000원',
    description: '불고기 소스를 올린 핫도그',
    imageUrl: 'https://placehold.co/100',
  },
];
