export const MOCK_MESSAGE_LIST = [
  {
    id: 1,
    message: '안녕하세요',
    time: '오후 2:00',
    date: '2024년 8월 30일',
    isMine: false,
    profileImage: 'https://placehold.co/40',
  },
  {
    id: 2,
    message: '혹시 거래 가능할까요?',
    time: '오후 2:01',
    date: '2024년 8월 30일',
    isMine: false,
  },
  {
    id: 3,
    message: '넵 가능할 것 같습니다.',
    time: '오후 3:00',
    date: '2024년 8월 30일',
    isMine: true,
    isRead: true,
  },
  {
    id: 4,
    message: '말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인',
    time: '오후 3:05',
    date: '2024년 8월 30일',
    isMine: true,
    isRead: true,
  },
  {
    id: 5,
    message: '말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인 말풍선 맥시멈 확인',
    time: '오후 3:05',
    date: '2024년 8월 30일',
    isMine: false,
    profileImage: 'https://placehold.co/40',
  },
  {
    id: 6,
    message: 'test',
    time: '오후 3:05',
    date: '2024년 8월 30일',
    isMine: false,
  },
  {
    id: 7,
    reservationMessageType: 'CONFIRMATION_SENT' as const,
    time: '오후 3:05',
    date: '2024년 8월 30일',
    isMine: true,
    isRead: true,
  },
  {
    id: 8,
    reservationMessageType: 'CONFIRMATION_REQUEST' as const,
    time: '오후 3:05',
    date: '2024년 8월 30일',
    isMine: false,
    profileImage: 'https://placehold.co/40',
  },
  {
    id: 9,
    reservationMessageType: 'RESERVATION_CONFIRMED' as const,
    time: '오후 3:10',
    date: '2024년 8월 30일',
    isMine: true,
    isRead: true,
  },
  {
    id: 10,
    reservationMessageType: 'CONFIRMATION_REQUEST' as const,
    isCancelled: true,
    time: '오후 3:10',
    date: '2024년 8월 30일',
    isMine: false,
    profileImage: 'https://placehold.co/40',
  },
  {
    id: 11,
    message: 'test',
    time: '오후 3:05',
    date: '2024년 8월 31일',
    isMine: false,
    profileImage: 'https://placehold.co/40',
  },
];
