import type { MyFoodTruckMenuResponse } from 'apis/data-contracts';

export const mockMenuData: MyFoodTruckMenuResponse[] = [
  {
    menuId: 1,
    imageUrl: 'https://placehold.co/80',
    name: 'Fajitas 화이타 1',
    description: '새우, 치킨, 돼지고기와 부재료를 또띠아에 싸먹는 멕시코 음식입니다.',
    price: '10000',
    status: 'ON',
  },
  {
    menuId: 2,
    imageUrl: 'https://placehold.co/80',
    name: 'Fajitas 화이타 2',
    description: '새우, 치킨, 돼지고기와 부재료를 또띠아에 싸먹는 멕시코 음식입니다.',
    price: '20000',
    status: 'ON',
  },
  {
    menuId: 3,
    imageUrl: 'https://placehold.co/80',
    name: 'Fajitas 화이타 3',
    description: '새우, 치킨, 돼지고기와 부재료를 또띠아에 싸먹는 멕시코 음식입니다.',
    price: '30000',
    status: 'OFF',
  },
  {
    menuId: 4,
    imageUrl: 'https://placehold.co/80',
    name: 'Fajitas 화이타 4',
    description: '새우, 치킨, 돼지고기와 부재료를 또띠아에 싸먹는 멕시코 음식입니다.',
    price: '40000',
    status: 'OFF',
  },
  {
    menuId: 5,
    imageUrl: 'https://placehold.co/80',
    name: 'Fajitas 화이타 5',
    description: '새우, 치킨, 돼지고기와 부재료를 또띠아에 싸먹는 멕시코 음식입니다.',
    price: '50000',
    status: 'ON',
  },
  {
    menuId: 6,
    imageUrl: 'https://placehold.co/80',
    name: 'Fajitas 화이타 6',
    description: '새우, 치킨, 돼지고기와 부재료를 또띠아에 싸먹는 멕시코 음식입니다.',
    price: '60000',
    status: 'ON',
  },
  {
    menuId: 7,
    imageUrl: 'https://placehold.co/80',
    name: 'Fajitas 화이타 7',
    description: '새우, 치킨, 돼지고기와 부재료를 또띠아에 싸먹는 멕시코 음식입니다.',
    price: '70000',
    status: 'ON',
  },
  {
    menuId: 8,
    imageUrl: 'https://placehold.co/80',
    name: 'Fajitas 화이타 8',
    description: '새우, 치킨, 돼지고기와 부재료를 또띠아에 싸먹는 멕시코 음식입니다.',
    price: '80000',
    status: 'ON',
  },
];
