export const mockup = [
  {
    foodTruckId: 1,
    name: '푸드트럭',
    photoUrl: 'https://placehold.co/100',
    description: '맛있는 푸드트럭입니다.',
    averageRating: 4.5,
    ratingCount: 100,
  },
  {
    foodTruckId: 2,
    name: '푸드트럭',
    photoUrl: 'https://placehold.co/80',
    description: '맛있는 푸드트럭입니다.',
    averageRating: 4.5,
    ratingCount: 100,
  },
  {
    foodTruckId: 3,
    name: '푸드트럭',
    photoUrl: 'https://placehold.co/80',
    description: '맛있는 푸드트럭입니다.',
    averageRating: 4.5,
    ratingCount: 100,
  },
  {
    foodTruckId: 4,
    name: '푸드트럭',
    photoUrl: 'https://placehold.co/80',
    description: '맛있는 푸드트럭입니다.',
    averageRating: 4.5,
    ratingCount: 100,
  },
  {
    foodTruckId: 5,
    name: '푸드트럭',
    photoUrl: 'https://placehold.co/80',
    description: '맛있는 푸드트럭입니다.',
    averageRating: 4.5,
    ratingCount: 100,
  },
];
