name: ci

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]'))
    runs-on: ubuntu-latest # 24.04(Ubuntu LTS)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        id: lint
        run: pnpm run lint
        continue-on-error: true

      - name: Build project with Vite
        id: build
        run: pnpm run build
        continue-on-error: true

      - name: Evaluate lint and build status
        id: status
        run: |
          lint_result="${{ steps.lint.outcome }}"
          build_result="${{ steps.build.outcome }}"
          
          lint_message=""
          build_message=""
          overall_result="success"
          
          if [ "$lint_result" == "success" ]; then
            lint_message="린트 통과 ✅"
          else
            lint_message="린트 실패 ❌"
            overall_result="failed"
          fi
          
          if [ "$build_result" == "success" ]; then
            build_message="빌드 성공 🎊"
          else
            build_message="빌드 실패 ❌"
            overall_result="failed"
          fi
          
          if [ "$overall_result" == "success" ]; then
            message="모든 검사 통과 🎉\n- $lint_message\n- $build_message"
          else
            message="일부 검사 실패 ⚠️\n- $lint_message\n- $build_message"
          fi

          echo "result=$overall_result" >> $GITHUB_OUTPUT
          echo "message=$message" >> $GITHUB_OUTPUT

      - name: Add comment to PR with status
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const message = `${{ steps.status.outputs.message }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `### 빌드 및 린트 결과\n${message}`
            });

      - name: Fail job if any step failed
        if: steps.check.outcome == 'failure' || steps.build.outcome == 'failure'
        run: exit 1